appmain/urls.py
from django.conf.urls import url

from . import views

app_name = 'appmain'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^plan/$', views.plan, name='plan'),
    url(r'^add_new_mail/$', views.add_new_mail, name='add_new_mail'),
    url(r'^sent_mail/$', views.sent_mail, name='sent_mail'),
]

sendmail/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', include('appmain.urls')),
]

appmain/models.py
from django.db import models

class Letter(models.Model):
    subject = models.CharField(null=False, blank=False, max_length=100)
    email = models.EmailField(null=False, blank=False)
    message = models.TextField(null=False, blank=False, max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    delay = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'

    def __str__(self):
        return f'{self.email} ({self.created})'

class SentLetter(models.Model):
    letter = models.ForeignKey(Letter, null=True, blank=True, on_delete=models.CASCADE)
    sent_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, default='не отправлено')

    class Meta:
        verbose_name = 'Отправленное письмо'
        verbose_name_plural = 'Отправленные письма'

    def __str__(self):
        return f'{self.letter} ({self.sent_date})'

appmain/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.core.mail import send_mail

from .models import Letter, SentLetter

def index(request):
    context = {}
    return render(request, 'appmain/index.html', context)


def plan(request):
    letter_qs = Letter.objects.all().order_by('-created')[0:10]
    letters = []
    for letter in letter_qs:
        sent_letter = SentLetter.objects.filter(letter=letter)
        if sent_letter:
            from datetime import datetime, timedelta
            letters.append({'letter': letter, 'plan_date': letter.created+timedelta(seconds=letter.delay), 'status': sent_letter[0].status})
        else:
            from datetime import datetime, timedelta
            letters.append({'letter': letter, 'plan_date': letter.created+timedelta(seconds=letter.delay), 'status': 'не отправлено'})

    context = {
        'letters': letters
    }
        
    return render(request, 'appmain/plan.html', context)


def add_new_mail(request):
    """
    Функция добавляет письмо в базу
    """
    mail_data = {
        'subject': 'Тестовое письмо',
        'email': request.POST.get('email'),
        'message': request.POST.get('message'),
        'delay': int(request.POST.get('delay')),
    }

    if mail_data['email'] and mail_data['message']:
        
        # создаем письмо
        Letter.objects.create(
            subject=f"Тестовое письмо. Задержка {mail_data['delay']} сек",
            email=mail_data['email'], 
            message=mail_data['message'],
            delay=mail_data['delay'],
        )

        # запускаем отправку всех писем
        sent_all_mails()

        return HttpResponseRedirect(reverse_lazy('appmain:plan'))
    else:
        return JsonResponse('Не все поля заполнены')

def sent_all_mails():
    
    import threading
    
    # создаем список тредов
    threads = []

    # получаем все письма из базы
    letters = Letter.objects.all()

    for letter in letters:
        
        if not SentLetter.objects.filter(letter=letter):
            
            # добавляем письмо в отправленные
            sent_letter = SentLetter.objects.create(letter=letter, status='ожидает отправки')

            # открываем тред для отправки письма
            t = threading.Thread(target=sent_mail, args=(letter, sent_letter, ))
            
            # добавляем тред в список тредов
            threads.append(t)

            # стартуем тред
            t.start()
            

    # закрываем все треды
    for t in threads:
        t.join()


def sent_mail(letter, sent_letter):
    """
    Функция для отправки письма
    """
    
    import time

    # Cпим. Время сна = задержка из письма (поле delay)
    time.sleep(letter.delay)
    
    # после сна отправляем письмо
    send_mail(
        letter.subject,
        letter.message,
        'dfpetrov@mail.ru',
        [letter.email],
    )

    sent_letter.status = 'отправлено'
    sent_letter.save()

    return JsonResponse({'response': 'ok'})

appmain/templates/appmain/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <div class="row" style="height: 100px;"></div>
        <div class="row">
            <div class="col-2 border rounded">
                <ol>
                    <li class="my-2"><a href="{% url 'appmain:index' %}">параметры письма</a></li>
                    <li class="my-2"><a href="{% url 'appmain:plan' %}">последние десять писем</a></li>
                </ol>
            </div>
            <div class="col-10">
                <form id="mail" method="post" action="">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Email address</label>
                        <input type="email" class="form-control" id="exampleFormControlInput1" name="email"
                            placeholder="name@example.com" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Текст письма</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="message"
                            required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">Задержка в секундах</label>
                        <select class="form-control" id="exampleFormControlSelect1" name="delay">
                            <option value="10">10</option>
                            <option value="20">20</option>
                            <option value="30">30</option>
                            <option value="40">40</option>
                            <option value="50">50</option>
                        </select>
                    </div>
                    <button type="button" class="btn btn-primary" id="btnSent">Отправить</button>
                </form>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>
        btnSent.onclick = function () {
            var postUrl = "{% url 'appmain:add_new_mail' %}"
            var formData = new FormData(document.forms.mail)
            var xhr = new XMLHttpRequest()
            xhr.open("POST", postUrl)
            xhr.send(formData)
            xhr.onloadend = function () {}


            Swal.fire({
                title: 'Письмо оправлено в очередь для отправки',
                text: "Смотреть очередь писем?",
                icon: 'info',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Да'
            }).then((result) => {
                if (result.value) {
                    window.location.href = "{% url 'appmain:plan' %}"
                }
            })
        }
    </script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>

appmain/templates/appmain/plan.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <div class="container-fluid">
        <div class="row" style="height: 100px;"></div>
        <div class="row">
            <div class="col-2 border rounded">
                <ol>
                    <li class="my-2"><a href="{% url 'appmain:index' %}">параметры письма</a></li>
                    <li class="my-2"><a href="">последние десять писем</a></li>
                </ol>
            </div>
            <div class="col-10">
                <a href="{% url 'appmain:plan' %}" class="btn btn-primary mb-2">Обновить</a>
                <table class="table table-hover table-dark">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Тема письма</th>
                            <th scope="col">email</th>
                            <th scope="col">Дата создания</th>
                            <th scope="col">Дата отправки</th>
                            <th scope="col">Статус</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for letter in letters %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ letter.letter.subject }}</td>
                            <td>{{ letter.letter.email }}</td>
                            <td>{{ letter.letter.created|date:"d.m.y H:i:s" }}</td>
                            <td>{{ letter.plan_date|date:"d.m.Y H:i:s" }}</td>
                            <td>{{ letter.status }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>